# Generated by Django 4.2.30 on 2026-09-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo do Filme', max_length=100, verbose_name='Titulos')),
                ('genero', models.CharField(help_text='Genero do Filme', max_length=100, verbose_name='Genero')),
                ('anoLançamento', models.DateField(help_text='Ano de lançamento do Filme', max_length=8, verbose_name='AnoLançamento')),
                ('valor', models.IntegerField(help_text='Valor do Filme', max_length=4, verbose_name='Valor')),
            ],
        ),
    ]
