# Generated by Django 4.2.30 on 2026-09-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filme',
            options={'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
        migrations.AlterField(
            model_name='filme',
            name='anoLançamento',
            field=models.CharField(help_text='Ano de lançamento do Filme', max_length=12, verbose_name='AnoLançamento'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='valor',
            field=models.CharField(help_text='Valor do Filme', max_length=4, verbose_name='Valor'),
        ),
    ]
